# ============================================================
# PLATFORM â€” ESP32 DEV KIT DO IT? idk (ARDUINO)
# ============================================================
#
# Defines:
# - MCU family
# - Framework
# - Board-level constraints
#
# This file MUST NOT:
# - define WiFi
# - define BLE
# - define sensors
# - define GPIO usage
#
# ============================================================

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino
